# Generated by Django 5.0.6 on 2024-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privet',
            field=models.BooleanField(default=False),
        ),
    ]
