# Generated by Django 5.0.6 on 2024-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_privet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='nafir.jpg', upload_to='profile_image'),
        ),
    ]
